apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ data.name }}
  namespace: {{ namespace }}
spec:
  schedule: "{{ data.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ data.name }}
            image: {{ data.image }}:{{ tag | default("latest", true) }}

            env:
              - name: TALISKER_NETWORKS
                value: 10.0.0.0/8

              {%- if data.useProxy is not defined or data.useProxy != False %}
              {% macro proxy_settings() %}{% include 'proxy-settings.yaml' %}{% endmacro %}
              {{ proxy_settings() | indent(14) }}
              {%- endif %}

              {%- if "env" in data %}
              {%- for env in data.env %}
              - name: {{ env.name }}
                {%- if "value" in env %}
                value: "{{ env.value }}"
                {%- endif %}

                {%- if "secretKeyRef" in env %}
                valueFrom:
                  secretKeyRef:
                    key: {{ env.secretKeyRef.key }}
                    name: {{ env.secretKeyRef.name }}
                {%- endif %}

                {%- if "configMapKeyRef" in env %}
                valueFrom:
                  configMapKeyRef:
                    key: {{ env.configMapKeyRef.key }}
                    name: {{ env.configMapKeyRef.name }}
                {%- endif %}
              {%- endfor %}
            {%- endif %}

            {%- if "run" in data %}
            args:
            - /bin/sh
            - -c
            - |
              {{ data.run | indent(14) }}
            {%- endif %}
          restartPolicy: Never
