---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ get_site_name(True) }}
  namespace: {{ namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/use-regex: "true"
    {%- if "nginxConfigurationSnippet" in data %}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      {{ data.nginxConfigurationSnippet | indent(6) }}
    {%- endif %}
    {%- if "nginxServerSnippet" in data %}
    nginx.ingress.kubernetes.io/server-snippet: |
      {{ data.nginxServerSnippet | indent(6) }}
    {%- endif %}
    {%- if data.nginxSSLRedirect is defined and not data.nginxSSLRedirect %}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {%- endif %}
  labels:
    app: "{{ data.get('app_name') or domain }}"
    {%- for key, value in labels.items() %}
    {{key}}: "{{value}}"
    {%- endfor %}

spec:
  {%- if data.noTls is not defined or not data.noTls %}
  tls:
  - secretName: {{ data.get('tlsName') or get_site_name(True) }}-tls

    hosts:
      - {{ get_environment_domain() }}
    {%- if (get_environment_domain() | is_apex_domain) %}
      - www.{{ get_environment_domain() }}
    {%- endif %}

    {%- if "extraHosts" in data %}
    {%- for host in data.extraHosts %}
      {%- if "useParentTLS" in host and host.useParentTLS %}
      - {{ host.domain | add_environment_prefix }}
      {%- if (host.domain | add_environment_prefix | is_apex_domain) %}
      - www.{{ host.domain | add_environment_prefix }}
      {%- endif %}
      {%- endif %}
    {% endfor %}
    {%- endif %}
  {%- endif %}

  {%- if "extraHosts" in data %}
  {%- for host in data.extraHosts %}
  {%- if host.useParentTLS is not defined or not host.useParentTLS %}
  - secretName: {{ host.domain | add_environment_prefix | replace(".", "-") }}-tls
    hosts:
      - {{ host.domain | add_environment_prefix }}
      {%- if (host.domain | add_environment_prefix | is_apex_domain) %}
      - www.{{ host.domain | add_environment_prefix }}
      {%- endif %}
  {%- endif %}
  {% endfor %}
  {%- endif %}

  rules:
  - host: {{ get_environment_domain() }}
    http: &http_service
      paths:
      {% if "routes" in data %}
      {%- for route in data.routes %}
      {%- for path in route.paths %}
      - path: {{ path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ route.get('service_name') or route.name }}
            port:
              number: 80
      {% endfor %}
      {% endfor %}
      {% endif %}

      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ get_site_name() }}
            port:
              number: 80

  {% if (get_environment_domain() | is_apex_domain) %}
  - host: www.{{ get_environment_domain() }}
    http: *http_service
  {%- endif %}

  {% if "extraHosts" in data %}
  {% for host in data.extraHosts %}
  - host: {{ host.domain | add_environment_prefix }}
    http: *http_service

  {%- if (host.domain | add_environment_prefix | is_apex_domain) %}
  - host: www.{{ host.domain | add_environment_prefix }}
    http: *http_service
  {%- endif %}
  {% endfor %}
  {%- endif %}
