{% include 'service.yaml' %}

{% if "routes" in data %}
{%- for route in data.routes %}
  {%- if route.service_name is not defined %}
    {%- with app_name=route.name, data=route %}
      {%- include 'service.yaml' %}
    {% endwith %}
  {% endif %}
{% endfor %}
{% endif %}

{% include 'deployment.yaml' %}

{% if "routes" in data %}
{%- for route in data.routes %}
  {%- if route.service_name is not defined %}
    {%- with app_name=route.name, data=route %}
      {%- include 'deployment.yaml' %}
    {% endwith %}
  {% endif %}
{% endfor %}
{% endif %}

{% if new_k8s_version %}
  {% include 'ingress-new.yaml' %}
{% else %}
  {% include 'ingress.yaml' %}
{% endif %}
