name: Tests
on: pull_request

jobs:
  test-snap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build Konf snap
        run: /snap/bin/snapcraft --destructive-mode

      - name: Install konf snap
        run: sudo snap install --dangerous konf_*.snap

      - uses: actions/upload-artifact@v4
        with:
          name: konf-snap
          path: konf_*.snap

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo pip3 install flake8 black

      - name: Lint Python
        run: flake8 . && black --line-length 79 --check .

  check-inclusive-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check inclusive naming
        uses: canonical-web-and-design/inclusive-naming@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail-on-error: true
